# ============================
#   Tema Alacritty - Terafox (TOML)
# ============================

[window]
opacity = 0.30
padding = { x = 10, y = 10 }

[font]
size = 12.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[colors.primary]
background = "#0f1c2e"
foreground = "#cbd6e2"

[colors.selection]
background = "#1e2d40"
foreground = "#cbd6e2"

[colors.cursor]
text = "#0f1c2e"
cursor = "#f6c177"

[colors.normal]
black = "#1a2a3a"
red = "#ff6b6b"
green = "#8bd49c"
yellow = "#ffd47e"
blue = "#5ab0f6"
magenta = "#c47fd5"
cyan = "#7cdce6"
white = "#cbd6e2"

[colors.bright]
black = "#223447"
red = "#ff7f7f"
green = "#9ce6ad"
yellow = "#ffdf99"
blue = "#6bc1ff"
magenta = "#d89fee"
cyan = "#8ceaf7"
white = "#e6eef5"

# Recarrega configurações ao salvar
[general]
live_config_reload = true
